"token"=""
"prefix"=";" # prefix used to denote commands
[music]
# Options for the music commands
"max_volume"=-1 # Max audio volume. Set to -1 for unlimited.
"vote_skip"=false # whether vote-skipping is enabled
"vote_skip_ratio"=0.5 # the minimum ratio of votes needed to skip a song
[tips]
"github_url"="https://github.com/joek13/py-music-bot"
